{"name": "test_冒烟测试2", "status": "failed", "statusDetails": {"message": "AssertionError: 断言失败\nassert 1 == 2", "trace": "self = <test_冒烟测试用例.Test_HSC3冒烟测试 object at 0x0000026F8473F448>\n\n    def test_冒烟测试2(self):\n        c = 1\n        d = 2\n>       assert c==d, \"断言失败\"\nE       AssertionError: 断言失败\nE       assert 1 == 2\n\nTestcase\\V2.0\\test_冒烟测试用例.py:21: AssertionError"}, "start": 1681377112819, "stop": 1681377112819, "uuid": "9a82dd47-0899-4316-81db-ea6ae3a3ae88", "historyId": "3fc1fbce9329459146ae79ba83137fa4", "testCaseId": "0ddc6b8db51c19f1093b1746ab97de8e", "fullName": "Testcase.V2.0.test_冒烟测试用例.Test_HSC3冒烟测试#test_冒烟测试2", "labels": [{"name": "parentSuite", "value": "Testcase.V2.0"}, {"name": "suite", "value": "test_冒烟测试用例"}, {"name": "subSuite", "value": "Test_HSC3冒烟测试"}, {"name": "host", "value": "DESKTOP-AS4K0DF"}, {"name": "thread", "value": "7612-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcase.V2.0.test_冒烟测试用例"}]}